name: Docker Build & Push
on:
  workflow_call:
    inputs:
      build_context:
        description: 'The build context. Will default to ., but can be overridden.'
        required: false
        type: string
      dockerfile_path:
        description: 'The full path to the Dockerfile. Will default to Dockerfile at root, but can be overridden.'
        required: false
        type: string
      image_name:
        description: 'The full name for the Docker image. For example: myrepo/myimage'
        required: true
        type: string
      image_tag:
        description: 'The image tag. If not provided, it will be the git commit SHA.'
        required: false
        type: string
jobs:
  docker_build_push:
    name: Build & Push ${{ inputs.image_name }}:${{ inputs.image_tag || github.sha }} Image
    env:
      full_image_path: '${{ inputs.image_name }}:${{ inputs.image_tag || github.sha }}'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ${{ inputs.build_context || '.' }}
          file: ${{ inputs.dockerfile_path || 'Dockerfile' }}
          tags: ${{ env.full_image_path }}
          build-args: ${{ secrets.build-args }}
